$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file

type: object

properties:
  general:
    work_dir:
      type: string
    region_file:
      type: string
    barcode_file_prefix:
      type: string
    library_file_prefix:
      type: string
    demux:
      type: boolean
  required:
    - work_dir
    - region
    - barcode_file
    - library_file
    - demux
  
  reference:
    genome:
      type: string
    known_indels:
      type: string
    required:
      - genome
      - known_indels

  illumina:
    basecall_dir:
      type: string
    readstructure:
      type: string
    runbarcode:
      type: string
    required:
      - basecall_dir
      - readstructure
      - runbarcode

  picard:
    memoryusage:
      type: string
    required:
      - memoryusage

  fgbio:
    groupreads:
      type: string
    callconsensus:
      type: string
    fextra:
      type: string
    fminq:
      type: integer
    required:
      - groupreads
      - callconsensus
      - fextra
      - fminq  

required:
  - general
  - reference
  - illumina
  - picard
  - fgbio
